import argparse
import csv
import json
from pathlib import Path
from typing import Dict, List, Any


def load_evaluations(path: Path) -> Dict[int, Dict[str, Any]]:
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return {int(item["person_id"]): item for item in data}


def load_potential(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)
    return rows


def filter_oceanus(potential_rows: List[Dict[str, str]], evaluations: Dict[int, Dict[str, Any]]):
    filtered = []
    for row in potential_rows:
        try:
            person_id = int(row["person_id"])
        except (KeyError, ValueError):
            continue
        evaluation = evaluations.get(person_id)
        if not evaluation:
            continue

        labels = evaluation.get("genre_labels", [])
        if "Oceanus Folk" not in labels:
            continue

        oceanus_share = evaluation.get("genre_share", {}).get("Oceanus Folk", 0.0)
        filtered.append({
            **row,
            "genre_labels": ",".join(labels),
            "oceanus_share": f"{oceanus_share:.4f}",
            "total_works_eval": evaluation.get("total_works", ""),
            "score": evaluation.get("score", ""),
        })
    return filtered


def write_csv(rows: List[Dict[str, str]], output_path: Path) -> None:
    if not rows:
        print("No Oceanus Folk artists found in potential list.")
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(rows[0].keys())
    with output_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(f"Saved {len(rows)} Oceanus Folk artists to {output_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Filter Oceanus Folk artists from potential list.")
    parser.add_argument(
        "--potential",
        type=Path,
        default=Path("genre-visualization/public/data/potential_artists_list.csv"),
        help="CSV file generated by potential.py",
    )
    parser.add_argument(
        "--evaluations",
        type=Path,
        default=Path("person_evaluations_labeled.json"),
        help="JSON file containing person evaluations with genre labels",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("output/potential_oceanus_artists.csv"),
        help="Destination CSV file for filtered artists",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if not args.potential.exists():
        raise FileNotFoundError(f"Potential list not found: {args.potential}")
    if not args.evaluations.exists():
        raise FileNotFoundError(f"Evaluations file not found: {args.evaluations}")

    evaluations = load_evaluations(args.evaluations)
    potential_rows = load_potential(args.potential)
    filtered_rows = filter_oceanus(potential_rows, evaluations)
    write_csv(filtered_rows, args.output)


if __name__ == "__main__":
    main()
